meta_product_name: "What's for dinner?"
meta_title: "What's for dinner? - The answer to the age old question"
meta_description: "Manage your pantry and find amazing recipes, everyday"
meta_image: "cover.png" # should exist in `app/assets/images/`
